### ISSUE TITLE
发现SSL的问题

### ISSUE THREAD

**Issue by linkmancheng** [sparklxb/docker-elasticsearch-kubernetes#1]
请问有没有遇到过这个问题：
javax.net.ssl.SSLPeerUnverifiedException: Hostname kubernetes.default.svc not verified:
    certificate: sha1/4xQd+1eSU89fBE1j3SolDM+61v8=
    DN: CN=host-172-216-0-17
    subjectAltNames: []
    at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:197)
    at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:145)
    at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:108)
    at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
    at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
    at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java

通过Kubectl logs 看master节点遇到这个问题。SSL证书应当是在装skydns的时候已经生成过，还需要生成么？

谢谢。

**Comment by sparklxb** [comment]
因为要翻墙，所以没按照官方文档装k8s，参考的是https://github.com/k8sp/hadoop/tree/master/init，不太了解这块
